language: groovy
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

install: true

script:
 - ./gradlew -S -i --console=plain --no-daemon clean build

jdk:
 - oraclejdk8

os:
 - linux

cache:
  directories:
    - $HOME/.gradle
