language: groovy

install:
 - ./gradlew clean

script:
 - ./gradlew -S -i build gradleTest

jdk:
 - oraclejdk7
 - oraclejdk8
 - openjdk7
 - openjdk6

os:
 - linux
 - osx

env: TERM=dumb

cache:
  directories:
    - $HOME/.gradle
