language: groovy
sudo: false
dist: trusty

install:
 - ./gradlew clean

script:
 - ./gradlew -S -i check gradleTest assemble

jdk:
 - oraclejdk8
 - openjdk7

os:
 - linux

env: TERM=dumb

cache:
  directories:
    - $HOME/.gradle
