version: "{branch} {build}"

build:
  verbosity: detailed

build_script:
  - gradlew.bat assemble --info

test_script:
  - gradlew.bat test check --info

branches:
  only:
    - master
    - development

